FROM rocker/shiny:4.0.5

RUN apt-get update
RUN apt-get install -y libcurl4-gnutls-dev \
   libssl-dev \
   libxml2-dev \
   nano

RUN R -q -e "install.packages('EasyABC',repos='http://cran.rstudio.com/')"

RUN R -q -e "install.packages('plotly',repos='http://cran.rstudio.com/')" && \
    R -q -e "install.packages('deSolve',repos='http://cran.rstudio.com/')" && \
    R -q -e "install.packages('tidyverse',repos='http://cran.rstudio.com/')" && \
    R -q -e "install.packages('dbplyr',repos='http://cran.rstudio.com/')" && \
    R -q -e "install.packages('pdfCluster',repos='http://cran.rstudio.com/')" && \
    R -q -e "install.packages('shinythemes',repos='http://cran.rstudio.com/')" && \
    R -q -e "install.packages('shinycssloaders',repos='http://cran.rstudio.com/')" && \
    R -q -e "install.packages('EpiModel',repos='http://cran.rstudio.com/')" && \
    R -q -e "install.packages('survival',repos='http://cran.rstudio.com/')" && \
    R -q -e "install.packages('EasyABC',repos='http://cran.rstudio.com/')" && \
    R -q -e "install.packages('viridis',repos='http://cran.rstudio.com/')" 
    

ADD ./source /srv/shiny-server/shiny

# run app
#CMD ["/usr/bin/shiny-server"]